export const formTypes = {
  baseInput: 'BASE_INPUT',
  numberInput: 'NUMBER_INPUT',
  baseSelect: 'BASE_SELECT',
  multiSelect: 'MULTI_SELECT',
  textarea: 'TEXTAREA',
  checkbox: 'CHECKBOX',
  colorPicker: 'COLOR_PICKER',
  primaryButton: 'PRIMARY_BUTTON',
  defaultButton: 'DEFAULT_BUTTON',
  dashedButton: 'DASHED_BUTTON',
};

export const droppableTypeTypes = {
  MENU: 'MENU',
  MENU_CHILDREN: 'MENU_CHILDREN',
  NAVIGATOR: 'NAVIGATOR',
  INFO_ICON: 'INFO_ICON',
  NAVIGATOR_INNER_ELEMENTS: 'NAVIGATOR_INNER_ELEMENTS',
};

export const droppableIdTypes = {
  CONTENT: 'CONTENT',
  CONTENT_CHILDREN: 'CONTENT_CHILDREN',
  INFO_ICON: 'INFO_ICON',
  MENU: 'MENU',
  MENU_CHILDREN: 'MENU_CHILDREN',
  NAVIGATOR_ELEMENTS: 'NAVIGATOR_ELEMENTS',
  NAVIGATOR_INNER_ELEMENTS: 'NAVIGATOR_INNER_ELEMENTS',
};

export const parsedSourceDroppableIdTypes = {
  MENU: 'MENU',
  MENU_CHILDREN: 'MENU_CHILDREN',
  NAVIGATOR_ELEMENTS: 'NAVIGATOR_ELEMENTS',
  CONTENT_CHILDREN: 'CONTENT_CHILDREN',
  INFO_ICON: 'INFO_ICON',
  NAVIGATOR_INNER_ELEMENTS: 'NAVIGATOR_INNER_ELEMENTS',
};

export const parsedDestinationDroppableIdTypes = {
  CONTENT: 'CONTENT',
  CONTENT_CHILDREN: 'CONTENT_CHILDREN',
  NAVIGATOR_ELEMENTS: 'NAVIGATOR_ELEMENTS',
  INFO_ICON: 'INFO_ICON',
  NAVIGATOR_INNER_ELEMENTS: 'NAVIGATOR_INNER_ELEMENTS',
};
